### ISSUE TITLE
Why some image(s) in assets/ and others in .gitbook/assets/ ?

### ISSUE THREAD

**Issue by olberger** [nre-learning/nrelabs-docs#2]
I'm a bit confused by the presence of documentation images both in assets/ and in .gitbook/assets/

For achitecture diagrams, I'd expect them to not be hidden under a hidden subdir like .gitbook/ and instead be "ordinary" content...

I'm probably overlooking some GitBook related details ?

**Comment by Mierdin** [comment]
The `.gitbook` repository is a gitbook convention, I don't know of a way to change it. I removed the assets directory at the root, as that didn't appear to be in use anywhere.
